### ISSUE TITLE
Support for actions

### ISSUE THREAD

**Issue by Aban** [sebsylvester/botbuilder-wit#1]
Hi,

Does this project support actions?. 
I am looking in the source but i can't find any way to do define my actions.

**Comment by sebsylvester** [comment]
Hi,
If I remember correctly, actions are part of Wit.ai's "Stories" feature which botbuilder-wit does not support (as mentioned in the docs). The reason for this is simple. Wit.ai's Stories feature is nothing more than a dialog system, which you already have, namely the botbuilder sdk.
