### ISSUE TITLE
Is Wit Intent State supported?

### ISSUE THREAD

**Issue by andhieka** [sebsylvester/botbuilder-wit#2]
Hi @sebsylvester. Kudos for this elegant library. Just a quick question - does this library support contextual intents? 

Contextual intent is described at https://wit.ai/blog/2014/02/20/dialog-state

**Comment by andhieka** [comment]
Briefly reading the code, it doesn't seem to be documented in [IWitContext](https://github.com/sebsylvester/botbuilder-wit/blob/ac79d22778021e9312ccb8facff8926cf4808c90/src/WitRecognizer.ts#L29). And empty WitContext is always passed to Wit [here](https://github.com/sebsylvester/botbuilder-wit/blob/ac79d22778021e9312ccb8facff8926cf4808c90/src/WitRecognizer.ts#L135).

I think it's a good idea to incorporate context in this library. But I'd like to first hear your advice and reasoning. Thank you!

**Comment by sebsylvester** [comment]
Hi, 
You're right that the WitContext is always empty. I had to include WitContext as a parameter to avoid TypeScript compiler issues. The reason for this is that the module was specifically designed for the botbuilder sdk, which is essentially a fancy dialog system. Every bit of context can be held in the dialog state (session.dialogData), and the sdk makes it easy to control dialog flow based on this state. Sending context to Wit.ai might save you a few lines of code, but it will also give Wit.ai some control over your dialog logic. I prefer to keep Wit as "dumb" as possible and simply use it as an intent and entity recognizer and control all dialog logic with the sdk.

**Comment by venomouse** [comment]
Hi sebsylvester, thanks for the library and for the explanation why you don't use Witcontext. I will mention, however, that not being able to pass context to Wit.ai interferes quite badly with datetime recognition - Wit.ai always returns the datetime in the same timezone (Pacific by default). If you're trying to work with users in different timezones, that creates a lot of mess. I am currently using a workaround (manually modifying the string in Wit.ai response), but it would make more sense to pass "timezone" context argument to Wit.ai.

**Comment by sebsylvester** [comment]
Hi, 
I'll take another look at it and try to find some time to fix it
