### ISSUE TITLE
'none' intent overrides correct intent when having multiple wit.ai models 

### ISSUE THREAD

**Issue by josephktcheung** [sebsylvester/botbuilder-wit#4]
Hi,

This library is awesome and easy to use, thanks!

I have a question though, we need to train multiple Wit.ai models in order to support multiple languages, let's say we want to identify "I want 1 coffee" and "我想要1杯咖啡" as an `Order` intent, `1` as `wit/number` entity and `coffee` as `item` entity. When English and Chinese Wit.ai models are trained, most likely one can only successfully interpreted 1 of the 2 utterances above with correct intent while the other utterance will have no intent but identify `number` entity of `1`.

In this situation, if we add the 2 Wit.ai models to botbuilder, if user types "I want 1 coffee", English wit.ai model returns something like this (just made it up):
```javascript
[
  {
    "confidence": null,
    "intent": "default_intent",
    "entities": {
      "item": [
        {
          "confidence": 1,
          "value": "coffee",
          "type": "value"
        }
      ],
      "number": [
        {
          "confidence": 1,
          "value": 1,
          "type": "value"
        }
      ],
      "intent": [
        {
          "confidence": 0.99998153138492,
          "value": "Order"
        }
      ]
    }
  }
]
```
and Chinese Wit.ai returns something like this:
```javascript
[
  {
    "confidence": null,
    "intent": "default_intent",
    "entities": {
      "number": [
        {
          "confidence": 1,
          "value": 1,
          "type": "value"
        }
      ]
    }
  }
]
```
According to current [logic](https://github.com/sebsylvester/botbuilder-wit/blob/master/src/WitRecognizer.ts#L167), even though Chinese Wit.ai doesn't have an intent, an intent of 'none' is passed with score of 1.0, making it more preferable than the correct English intent which has a score of less than 1.0.

This is actually [addressed in botbuilder's `LuisRecognizer` comment](https://github.com/Microsoft/BotBuilder/blob/e26ea2404724238ac64c701e493c0f005b0f3444/Node/core/src/dialogs/LuisRecognizer.ts#L82):
> Correct score for 'none' intent
> - The 'none' intent often has a score of 1.0 which causes issues when trying to recognize over multiple models. Setting to 0.1 lets the intent still be triggered but keeps it from stomping on other models.

Therefore, I believe we should have the same mechanic as `LuisRecognizer` on handling `none` intent (`none` intent score = 0.1) so that this library can support multiple models.

Thanks,
Joseph

**Comment by sebsylvester** [comment]
Thanks for the pull request.

**Comment by josephktcheung** [comment]
Thanks @sebsylvester for merging my pull request, however, the latest package installed from npm is not updated yet (score is still 1.0). I wonder if you forgot to build before publishing.

**Comment by sebsylvester** [comment]
Sorry about that. I was in a rush, and that's when stuff like that happens :)
