### ISSUE TITLE
Having trouble with global triggers

### ISSUE THREAD

**Issue by haakotsm** [sebsylvester/botbuilder-wit#6]
I've registered the recognizer with the bot, and added a couple of global listeners for help and cancel. Help uses a request_help intent, while the cancel uses regEx. The regEx will register inside both dialogs and prompts. 

The intent however won't register inside dialogs, unless it's the root dialog. 

``` 
const {recognizer} = require('./src/helpers/witRecognizer');

/*
* Steps for setting up the botbuilder connection and server
*/

// Wit.ai recognizer, input blir sendt hit for å tolke intent.
bot.recognizer(recognizer);

//Dialog for hilsninger
bot.dialog('greet_dialog', dialogs.greet).triggerAction({
    matches: 'greet', onSelectAction: (session, args) => {
        session.beginDialog(args.action, args);
    }
});

// Dialog for å etterspørre en oppskrift.
bot.dialog("request_recipe_dialog", dialogs.requestRecipe).triggerAction({
    matches: 'request_recipe',
});
// Dialog for å etterspørre en spesifikk oppskrift
bot.dialog('specific_recipe_dialog', dialogs.specificRecipe);

// Global lytter for hjelp
bot.beginDialogAction('help_action', '/help_dialog', {matches: 'help'});

// Global lytter for å avbryte en samtale
bot.endConversationAction('cancelAction', "Avbrutt", {
    matches: /^cancel|avbryt|exit|restart|start på nytt$/i
});

// Dialog for hjelp med bot'en
bot.dialog('/help_dialog', dialogs.help);

```

**Comment by sebsylvester** [comment]
I don't think there's an issue with the botbuilder-wit module.
In your code you're matching an intent named 'help'. But you also mentioned an intent named 'request_help'. Perhaps you made a mistake in you code. If that doesn't work, I would suggest to do some debugging and find out what code is executed when the bot receives the 'help' message.

**Comment by haakotsm** [comment]
It was a regEx earlier, forgot to change it all they way to request_help.

the line `bot.beginDialogAction('help_action', 'help_dialog', {matches: 'request_help'});`

Should it not trigger when I'm inside other dialogs? I am pretty sure I've made some mistake somewhere, but I'm not able to see it. While inside the request_recipe_dialog if it catches any other intent, it stops working and announces `..BotBuilder:prompt-text - WARN: Prompt - no intent handler found for request_help`

Is this something you're familiar with? If no, I'll continue my search.  I'm not using the IntentDialog class.

**Comment by sebsylvester** [comment]
I think I found the bug in your code. When you invoke `bot.dialog('/help_dialog', dialogs.help);` it registers the help dialog with the id string `/help_dialog`. So, referring to it as `help_dialog` explains the warning message `...WARN: Prompt - no intent handler found for request_help`.

**Comment by sebsylvester** [comment]
How do you reference the help dialog? Is it with `help_dialog` or `/help_dialog`. It should be the exact same string that was used to register the dialog with the bot, in this case `/help_dialog`. But in your previous comment you mention `bot.beginDialogAction('help_action', 'help_dialog', {matches: 'request_help'});`. This could explain the warning message. If that does not help, then you might find more clues in the bot's log statements.

**Comment by haakotsm** [comment]
that is an oversight on my part. I've changed all the dialog paths to constants, so I'm sure they're exactly alike.

**Comment by sebsylvester** [comment]
The dialog paths and ID's are not the same. 
The statement `bot.dialog('/help_dialog', dialogs.help);` creates the id `/help_dialog` which starts whatever dialog is referenced as the second argument. When using `bot.beginDialogAction`, the second argument should exactly match the dialog id.

**Comment by haakotsm** [comment]
Yes, that's what I was supposed to say. This is how it looks with the constants.
`
bot.beginDialogAction('help_action', DIALOGS.REQUEST_HELP, {matches: INTENTS.REQUEST_HELP});
bot.dialog(DIALOGS.REQUEST_HELP, dialogs.help);
`

**Comment by sebsylvester** [comment]
You could also try to simplify things by removing the global help_action and register the help dialog with `bot.dialog(DIALOGS.REQUEST_HELP, dialogs.help).triggerAction({ matches: /^help/i });`. According to the docs, the default behavior is to interrupt any existing dialog by clearing the stack and starting the dialog at the root of the stack. 

As an aside. It looks like the warning message is generated by a function named `invokeIntent` => https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/dialogs/Prompt.ts#L397
Setting a breakpoint at the top of the function and then step through it could give further insight as to what is happening under the hood.

Other than that, I'm out of ideas.

**Comment by haakotsm** [comment]
Alright, thanks alot. I was hoping it would work with intent, rathen than a regEx. I'll try the breakpoint as well.

**Comment by haakotsm** [comment]
It seems the intent handler within the prompt isn't aware of any intents other than BotBuilder.ResponseIntent. Are you aware if it's possible to register other intents for it to catch?

**Comment by haakotsm** [comment]
After further investigation I figured out how to customize the prompt to match with my intents. I'm not sure if it's the best solution, but it works.
